const euCommand1920C = [
  {
    flag_country: "hr.png",
    country: "Хорватия",
    game_count: 7,
    board_total_win: 22,
    board_1_win: 6,
    board_2_win: 5,
    board_3_win: 5,
    board_4_win: 6,
    game_win: 5,
    game_draw: 1,
    game_loos: 1,
    game_lose: 11
  },
  {
    flag_country: "ie.png",
    country: "Ирландия",
    game_count: 7,
    board_total_win: 18,
    board_1_win: 2,
    board_2_win: 6,
    board_3_win: 5,
    board_4_win: 6,
    game_win: 5,
    game_draw: 1,
    game_loos: 1,
    game_lose: 11
  },
  {
    flag_country: "za.png",
    country: "Южная Африка",
    game_count: 7,
    board_total_win: 17,
    board_1_win: 6,
    board_2_win: 3,
    board_3_win: 5,
    board_4_win: 3,
    game_win: 3,
    game_draw: 3,
    game_loos: 1,
    game_lose: 9
  },
  {
    flag_country: "sk.png",
    country: "Словакия",
    game_count: 7,
    board_total_win: 15,
    board_1_win: 5,
    board_2_win: 4,
    board_3_win: 4,
    board_4_win: 2,
    game_win: 2,
    game_draw: 4,
    game_loos: 1,
    game_lose: 8
  },
  {
    flag_country: "dk.png",
    country: "Дания",
    game_count: 7,
    board_total_win: 12,
    board_1_win: 4,
    board_2_win: 3,
    board_3_win: 1,
    board_4_win: 4,
    game_win: 2,
    game_draw: 2,
    game_loos: 3,
    game_lose: 6
  },
  {
    flag_country: "no.png",
    country: "Норвегия",
    game_count: 7,
    board_total_win: 12,
    board_1_win: 1,
    board_2_win: 5,
    board_3_win: 4,
    board_4_win: 2,
    game_win: 1,
    game_draw: 4,
    game_loos: 2,
    game_lose: 6
  },
  {
    flag_country: "gr.png",
    country: "Греция",
    game_count: 7,
    board_total_win: 8,
    board_1_win: 3,
    board_2_win: 0,
    board_3_win: 3,
    board_4_win: 2,
    game_win: 0,
    game_draw: 3,
    game_loos: 4,
    game_lose: 3
  },
  {
    flag_country: "si.png",
    country: "Словения",
    game_count: 7,
    board_total_win: 8,
    board_1_win: 1,
    board_2_win: 2,
    board_3_win: 2,
    board_4_win: 3,
    game_win: 1,
    game_draw: 0,
    game_loos: 6,
    game_lose: 2
  }
];

module.exports = euCommand1920C;