const euCommand1920B = [
  {
    flag_country: "rs.png",
    country: "Сербия",
    game_count: 9,
    board_total_win: 26,
    board_1_win: 6,
    board_2_win: 9,
    board_3_win: 6,
    board_4_win: 5,
    game_win: 6,
    game_draw: 2,
    game_loos: 1,
    game_lose: 14
  },
  {
    flag_country: "it.png",
    country: "Италия",
    game_count: 9,
    board_total_win: 25,
    board_1_win: 5,
    board_2_win: 7,
    board_3_win: 8,
    board_4_win: 5,
    game_win: 5,
    game_draw: 3,
    game_loos: 1,
    game_lose: 13
  },
  {
    flag_country: "fi.png",
    country: "Финляндия",
    game_count: 9,
    board_total_win: 20,
    board_1_win: 6,
    board_2_win: 5,
    board_3_win: 5,
    board_4_win: 4,
    game_win: 3,
    game_draw: 5,
    game_loos: 1,
    game_lose: 11
  },
  {
    flag_country: "tr.png",
    country: "Турция",
    game_count: 9,
    board_total_win: 20,
    board_1_win: 4,
    board_2_win: 6,
    board_3_win: 5,
    board_4_win: 6,
    game_win: 5,
    game_draw: 1,
    game_loos: 3,
    game_lose: 11
  },
  {
    flag_country: "be.png",
    country: "Бельгия",
    game_count: 9,
    board_total_win: 20,
    board_1_win: 9,
    board_2_win: 4,
    board_3_win: 3,
    board_4_win: 4,
    game_win: 2,
    game_draw: 5,
    game_loos: 2,
    game_lose: 9
  },
  {
    flag_country: "gb.png",
    country: "Великобритания",
    game_count: 9,
    board_total_win: 17,
    board_1_win: 6,
    board_2_win: 2,
    board_3_win: 4,
    board_4_win: 5,
    game_win: 3,
    game_draw: 2,
    game_loos: 4,
    game_lose: 8
  },
  {
    flag_country: "ch.png",
    country: "Швейцария",
    game_count: 9,
    board_total_win: 17,
    board_1_win: 3,
    board_2_win: 4,
    board_3_win: 4,
    board_4_win: 6,
    game_win: 2,
    game_draw: 4,
    game_loos: 3,
    game_lose: 8
  },
  {
    flag_country: "nl.png",
    country: "Нидерланды",
    game_count: 9,
    board_total_win: 15,
    board_1_win: 3,
    board_2_win: 5,
    board_3_win: 3,
    board_4_win: 4,
    game_win: 3,
    game_draw: 2,
    game_loos: 4,
    game_lose: 8
  },
  {
    flag_country: "se.png",
    country: "Швеция",
    game_count: 9,
    board_total_win: 11,
    board_1_win: 3,
    board_2_win: 3,
    board_3_win: 3,
    board_4_win: 5,
    game_win: 2,
    game_draw: 3,
    game_loos: 4,
    game_lose: 7
  },
  {
    flag_country: "lt.png",
    country: "Литва",
    game_count: 9,
    board_total_win: 1,
    board_1_win: 0,
    board_2_win: 0,
    board_3_win: 4,
    board_4_win: 1,
    game_win: 0,
    game_draw: 1,
    game_loos: 8,
    game_lose: 0
  }
];

module.exports = euCommand1920B;