const euCommand1920A = [
  {
    "flag_country": "ru.png",
    "country": "Россия",
    "game_count": 9,
    "board_total_win": 29,
    "board_1_win": 7,
    "board_2_win": 7,
    "board_3_win": 7,
    "board_4_win": 8,
    "game_win": 7,
    "game_draw": 2,
    "game_loos": 0,
    "game_lose": 16
  },
  {
    "flag_country": "fr.png",
    "country": "Франция",
    "game_count": 9,
    "board_total_win": 24,
    "board_1_win": 4,
    "board_2_win": 7,
    "board_3_win": 8,
    "board_4_win": 5,
    "game_win": 6,
    "game_draw": 2,
    "game_loos": 1,
    "game_lose": 14
  },
  {
    "flag_country": "cz.png",
    "country": "Чехия",
    "game_count": 9,
    "board_total_win": 22,
    "board_1_win": 6,
    "board_2_win": 4,
    "board_3_win": 4,
    "board_4_win": 8,
    "game_win": 6,
    "game_draw": 2,
    "game_loos": 1,
    "game_lose": 14
  },
  {
    "flag_country": "ua.png",
    "country": "Украина",
    "game_count": 9,
    "board_total_win": 21,
    "board_1_win": 6,
    "board_2_win": 8,
    "board_3_win": 4,
    "board_4_win": 3,
    "game_win": 3,
    "game_draw": 5,
    "game_loos": 1,
    "game_lose": 11
  },
  {
    "flag_country": "ro.png",
    "country": "Румыния",
    "game_count": 9,
    "board_total_win": 17,
    "board_1_win": 4,
    "board_2_win": 3,
    "board_3_win": 7,
    "board_4_win": 4,
    "game_win": 4,
    "game_draw": 2,
    "game_loos": 3,
    "game_lose": 10
  },
  {
    "flag_country": "pl.png",
    "country": "Польша",
    "game_count": 9,
    "board_total_win": 14,
    "board_1_win": 4,
    "board_2_win": 5,
    "board_3_win": 2,
    "board_4_win": 3,
    "game_win": 3,
    "game_draw": 1,
    "game_loos": 5,
    "game_lose": 7
  },
  {
    "flag_country": "hu.png",
    "country": "Венгрия",
    "game_count": 9,
    "board_total_win": 13,
    "board_1_win": 4,
    "board_2_win": 3,
    "board_3_win": 4,
    "board_4_win": 4,
    "game_win": 2,
    "game_draw": 2,
    "game_loos": 5,
    "game_lose": 6
  },
  {
    "flag_country": "at.png",
    "country": "Австрия",
    "game_count": 9,
    "board_total_win": 13,
    "board_1_win": 4,
    "board_2_win": 2,
    "board_3_win": 3,
    "board_4_win": 4,
    "game_win": 1,
    "game_draw": 3,
    "game_loos": 5,
    "game_lose": 5
  },
  {
    "flag_country": "il.png",
    "country": "Израиль",
    "game_count": 9,
    "board_total_win": 13,
    "board_1_win": 5,
    "board_2_win": 3,
    "board_3_win": 2,
    "board_4_win": 3,
    "game_win": 1,
    "game_draw": 2,
    "game_loos": 6,
    "game_lose": 4
  },
  {
    "flag_country": "de.png",
    "country": "Германия",
    "game_count": 9,
    "board_total_win": 11,
    "board_1_win": 1,
    "board_2_win": 3,
    "board_3_win": 4,
    "board_4_win": 3,
    "game_win": 0,
    "game_draw": 3,
    "game_loos": 6,
    "game_lose": 3
  }
];

module.exports = euCommand1920A;