const euCommand1920D = [
  {
    "flag_country": "es.png",
    "country": "Испания",
    "game_count": 8,
    "board_total_win": 26,
    "board_1_win": 3,
    "board_2_win": 7,
    "board_3_win": 8,
    "board_4_win": 8,
    "game_win": 7,
    "game_draw": 1,
    "game_loos": 0,
    "game_lose": 15
  },
  {
    "flag_country": "bg.png",
    "country": "Болгария",
    "game_count": 8,
    "board_total_win": 24,
    "board_1_win": 8,
    "board_2_win": 7,
    "board_3_win": 4,
    "board_4_win": 5,
    "game_win": 6,
    "game_draw": 2,
    "game_loos": 0,
    "game_lose": 14
  },
  {
    "flag_country": "by.png",
    "country": "Беларусь",
    "game_count": 8,
    "board_total_win": 19,
    "board_1_win": 4,
    "board_2_win": 5,
    "board_3_win": 6,
    "board_4_win": 4,
    "game_win": 5,
    "game_draw": 1,
    "game_loos": 2,
    "game_lose": 11
  },
  {
    "flag_country": "cy.png",
    "country": "Кипр",
    "game_count": 8,
    "board_total_win": 18,
    "board_1_win": 6,
    "board_2_win": 4,
    "board_3_win": 5,
    "board_4_win": 4,
    "game_win": 4,
    "game_draw": 2,
    "game_loos": 2,
    "game_lose": 10
  },
  {
    "flag_country": "pt.png",
    "country": "Португалия",
    "game_count": 8,
    "board_total_win": 17,
    "board_1_win": 4,
    "board_2_win": 4,
    "board_3_win": 3,
    "board_4_win": 6,
    "game_win": 3,
    "game_draw": 1,
    "game_loos": 4,
    "game_lose": 7
  },
  {
    "flag_country": "kz.png",
    "country": "Казахстан",
    "game_count": 8,
    "board_total_win": 13,
    "board_1_win": 3,
    "board_2_win": 3,
    "board_3_win": 6,
    "board_4_win": 1,
    "game_win": 1,
    "game_draw": 3,
    "game_loos": 4,
    "game_lose": 5
  },
  {
    "flag_country": "is.png",
    "country": "Исландия",
    "game_count": 8,
    "board_total_win": 9,
    "board_1_win": 4,
    "board_2_win": 4,
    "board_3_win": 2,
    "board_4_win": 3,
    "game_win": 3,
    "game_draw": 0,
    "game_loos": 5,
    "game_lose": 5
  },
  {
    "flag_country": "ge.png",
    "country": "Грузия",
    "game_count": 8,
    "board_total_win": 13,
    "board_1_win": 4,
    "board_2_win": 2,
    "board_3_win": 2,
    "board_4_win": 5,
    "game_win": 1,
    "game_draw": 2,
    "game_loos": 5,
    "game_lose": 4
  },
  {
    "flag_country": "ma.png",
    "country": "Марокко",
    "game_count": 8,
    "board_total_win": 0,
    "board_1_win": 0,
    "board_2_win": 0,
    "board_3_win": 0,
    "board_4_win": 0,
    "game_win": 0,
    "game_draw": 0,
    "game_loos": 8,
    "game_lose": 0
  }
];

module.exports = euCommand1920D;