const util = require("./util.js");

let euPersonal = [
  {"year":"1957","g_country":"Германия","g_name":"Фриц Дюбаль","g_flag":"de.png","country":"Германия","city":"Куксхафен","flag":"de.png"},
  {"year":"1958","g_country":"Германия","g_name":"Фриц Дюбаль","g_flag":"de.png","country":"Австрия","city":"Альтенмаркт-ан-дер-Тристинг","flag":"at.png"},
  {"year":"1959","g_country":"Германия","g_name":"Фриц Дюбаль","g_flag":"de.png","country":"Германия","city":"Байройт","flag":"de.png"},
  {"year":"1960","g_country":"Германия","g_name":"Гюнтер Гьессов","g_flag":"de.png","country":"Нидерланды","city":"Лейден","flag":"nl.png"},
  {"year":"1961","g_country":"Германия","g_name":"Вихард фон Алвенслебен","g_flag":"de.png","country":"Австрия","city":"Баден","flag":"at.png"},
  {"year":"1962","g_country":"Германия","g_name":"Вихард фон Алвенслебен","g_flag":"de.png","country":"Германия","city":"Гармиш-Партенкирхен","flag":"de.png"},
  {"year":"1963","g_country":"Германия","g_name":"Вихард фон Алвенслебен","g_flag":"de.png","country":"Германия","city":"Барзингхаузен","flag":"de.png"},
  {"year":"1964","g_country":"Германия","g_name":"Вихард фон Алвенслебен","g_flag":"de.png","country":"Нидерланды","city":"Схевенинген","flag":"nl.png"},
  {"year":"1965","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Чехословакия","city":"Мнишек-под-Брди","flag":"cz.png"},
  {"year":"1966","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Великобритания","city":"Лондон","flag":"gb.png"},
  {"year":"1967","g_country":"Югославия","g_name":"Зоран Мутабзя","g_flag":"yu.jpg","country":"Германия","city":"Штауфен-им-Брайсгау","flag":"de.png"},
  {"year":"1968","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Германия","city":"Берлин","flag":"de.png"},
  {"year":"1969","g_country":"Австрия","g_name":"Манфред Виммер","g_flag":"at.png","country":"Югославия","city":"Любляна","flag":"yu.jpg"},
  {"year":"1970","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Австрия","city":"Вена","flag":"at.png"},
  {"year":"1971","g_country":"Югославия","g_name":"Зоран Мутабзя","g_flag":"yu.jpg","country":"Великобритания","city":"Бристоль","flag":"gb.png"},
  {"year":"1972","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Нидерланды","city":"Энсхеде","flag":"nl.png"},
  {"year":"1973","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Германия","city":"Шпрендлинген","flag":"de.png"},
  {"year":"1974","g_country":"Австрия","g_name":"Манфред Виммер","g_flag":"at.png","country":"Югославия","city":"Загреб","flag":"yu.jpg"},
  {"year":"1975","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Австрия","city":"Кремс-на-Дунае","flag":"at.png"},
  {"year":"1976","g_country":"Франция","g_name":"Патрик Мериссерт","g_flag":"fr.png","country":"Великобритания","city":"Кембридж","flag":"gb.png"},
  {"year":"1977","g_country":"Германия","g_name":"Вольфганг Изель","g_flag":"de.png","country":"Нидерланды","city":"Рейсвейк","flag":"nl.png"},
  {"year":"1978","g_country":"Австрия","g_name":"Гельмут Газибедер","g_flag":"at.png","country":"Франция","city":"Париж","flag":"fr.png"},
  {"year":"1979","g_country":"Германия","g_name":"Юрген Маттерн","g_flag":"de.png","country":"Германия","city":"Кёнигсвинтер","flag":"de.png"},
  {"year":"1980","g_country":"Великобритания","g_name":"Мэттью Макфейден","g_flag":"gb.png","country":"Югославия","city":"Мали-Лошинь","flag":"yu.jpg"},
  {"year":"1981","g_country":"Нидерланды","g_name":"Роб ван Зайст","g_flag":"nl.png","country":"Австрия","city":"Линц","flag":"at.png"},
  {"year":"1982","g_country":"Нидерланды","g_name":"Рональд Шлемпер","g_flag":"nl.png","country":"Дания","city":"Копенгаген","flag":"dk.png"},
  {"year":"1983","g_country":"Польша","g_name":"Януш Крашек","g_flag":"pl.png","country":"Великобритания","city":"Эдинбург","flag":"gb.png"},
  {"year":"1984","g_country":"Великобритания","g_name":"Мэттью Макфейден","g_flag":"gb.png","country":"Швейцария","city":"Поррантрюи","flag":"ch.png"},
  {"year":"1985","g_country":"Великобритания","g_name":"Мэттью Макфейден","g_flag":"gb.png","country":"Нидерланды","city":"Терсхеллинг","flag":"nl.png"},
  {"year":"1986","g_country":"Нидерланды","g_name":"Рональд Шлемпер","g_flag":"nl.png","country":"Венгрия","city":"Будапешт","flag":"hu.png"},
  {"year":"1987","g_country":"Великобритания","g_name":"Мэттью Макфейден","g_flag":"gb.png","country":"Франция","city":"Гренобль","flag":"fr.png"},
  {"year":"1988","g_country":"Венгрия","g_name":"Тибор Почай","g_flag":"hu.png","country":"Германия","city":"Гамбург","flag":"de.png"},
  {"year":"1989","g_country":"Великобритания","g_name":"Мэттью Макфейден","g_flag":"gb.png","country":"Югославия","city":"Ниш","flag":"yu.jpg"},
  {"year":"1990","g_country":"Нидерланды","g_name":"Роб ван Зайст","g_flag":"nl.png","country":"Австрия","city":"Вена","flag":"at.png"},
  {"year":"1991","g_country":"СССР","g_name":"Алексей Лазарев","g_flag":"sssr.gif","country":"Бельгия","city":"Намюр","flag":"be.png"},
  {"year":"1992","g_country":"Россия","g_name":"Алексей Лазарев","g_flag":"ru.png","country":"Великобритания","city":"Кентербери","flag":"gb.png"},
  {"year":"1993","g_country":"Нидерланды","g_name":"Роб ван Зайст","g_flag":"nl.png","country":"Чехия","city":"Прага","flag":"cz.png"},
  {"year":"1994","g_country":"Нидерланды","g_name":"Го Цзюань","g_flag":"nl.png","country":"Нидерланды","city":"Маастрихт","flag":"nl.png"},
  {"year":"1995","g_country":"Нидерланды","g_name":"Го Цзюань","g_flag":"nl.png","country":"Польша","city":"Тухоля","flag":"pl.png"},
  {"year":"1996","g_country":"Нидерланды","g_name":"Го Цзюань","g_flag":"nl.png","country":"Италия","city":"Абано-Терме","flag":"it.png"},
  {"year":"1997","g_country":"Нидерланды","g_name":"Го Цзюань","g_flag":"nl.png","country":"Франция","city":"Марсель","flag":"fr.png"},
  {"year":"1998","g_country":"Румыния","g_name":"Роберт Матеску","g_flag":"ro.png","country":"Румыния","city":"Мамая","flag":"ro.png"},
  {"year":"1999","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Словакия","city":"Подбанске","flag":"sk.png"},
  {"year":"2000","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Германия","city":"Штраусберг","flag":"de.png"},
  {"year":"2001","g_country":"Россия","g_name":"Андрей Кульков","g_flag":"ru.png","country":"Ирландия","city":"Дублин","flag":"ie.png"},
  {"year":"2002","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Хорватия","city":"Загреб","flag":"hr.png"},
  {"year":"2003","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Россия","city":"Санкт-Петербург","flag":"ru.png"},
  {"year":"2004","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Польша","city":"Тухоля","flag":"pl.png"},
  {"year":"2005","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Чехия","city":"Прага","flag":"cz.png"},
  {"year":"2006","g_country":"Россия","g_name":"Светлана Шикшина","g_flag":"ru.png","country":"Италия","city":"Фраскати","flag":"it.png"},
  {"year":"2007","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Австрия","city":"Филлах","flag":"at.png"},
  {"year":"2008","g_country":"Румыния","g_name":"Каталин Тарану","g_flag":"ro.png","country":"Швеция","city":"Лександ","flag":"se.png"},
  {"year":"2009","g_country":"Россия","g_name":"Александр Динерштейн","g_flag":"ru.png","country":"Нидерланды","city":"Гронинген","flag":"nl.png"},
  {"year":"2010","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Финляндия","city":"Тампере","flag":"fi.png"},
  {"year":"2011","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Франция","city":"Бордо","flag":"fr.png"},
  {"year":"2012","g_country":"Чехия","g_name":"Ян Симара","g_flag":"cz.png","country":"Германия","city":"Бонн","flag":"de.png"},
  {"year":"2013","g_country":"Франция","g_name":"Фань Хуэй","g_flag":"fr.png","country":"Польша","city":"Ольштын","flag":"pl.png"},
  {"year":"2014","g_country":"Франция","g_name":"Фань Хуэй","g_flag":"fr.png","country":"Румыния","city":"Сибиу","flag":"ro.png"},
  {"year":"2015","g_country":"Франция","g_name":"Фань Хуэй","g_flag":"fr.png","country":"Чехия","city":"Либерец","flag":"cz.png"},
  {"year":"2016","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Россия","city":"Санкт-Петербург","flag":"ru.png"},
  {"year":"2017","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Германия","city":"Оберхоф","flag":"de.png"},
  {"year":"2018","g_country":"Словения","g_name":"Павол Лисий","g_flag":"si.png","country":"Италия","city":"Пиза","flag":"it.png"},
  {"year":"2019","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Бельгия","city":"Брюссель","flag":"be.png"},
  {"year":"2020","g_country":"Россия","g_name":"Илья Шикшин","g_flag":"ru.png","country":"Интернет","city":"Интернет","flag":"panda.jpg"}
];

euPersonal.sort(util.decreaseByNumberField("year"));
module.exports = euPersonal;